### PR TITLE
AutoAnswering

### PR DESCRIPTION
**Pull request by Ijwu**
http://tshock.co/xf/index.php?threads/autoanswerer.2112/

Sorry if you were already doing this/done. I wanted something to do. :)

Anyway, new config option called "TriggerWords". It is a list of strings. If any words are said in chat that are in that list it will automatically broadcast the appropriate broadcast. 

It will **not** reset interval timers.
It will **not** broadcast to all players.

If there are groups specified then it will broadcast to those groups. If there are no groups then it will only broadcast to that one player. 

It does **not** regard the "Enabled" option in the config. It will always respond no matter.

Most of the choices I made vary by taste. So here's most of the work done and you can tweak it to work in the way you want your plugin to work.

### CODE REVIEW

**Comment by Olink** [comment]
Should add support for it only checking certain groups for words, so that normal users arent being told to /register to register an account

**Comment by Ijwu** [comment]
Alright. Now if the broadcast has a group designation it will only respond to people in those groups. Yes, this means it's impossible to respond to only one player in a specific group. Again, it's a taste thing for scavenger to tweak.

Edit: I also didn't want to saturate the config with a bunch of crap. I'm trying to leave as much out of it as possible.

**Comment by Scavenger3** [comment]
It looks good to me, although there is one tweak that I would like to make...

If the broadcast is disabled it won't check the triggers.. However if you only want triggers when it is enabled, you can set the interval to 0.

Also shouldn't line 102 of PluginMain.cs be `continue;`

**Comment by Ijwu** [comment]
Yup, it should be. That's fixed.

Edit: Added in the tweak you mentioned.

**Comment by Scavenger3** [comment]
Thanks for doing it for me, just been busy with other stuff, but I'll quickly test it out now and update the thread.
edit: works a charm, thanks a lot...
I'm planning on updating the config editor to something web-based :) which should be fun.

**Pull request merged**
